name: 'WCAG Accessibility Scanner'
description: 'Scan your website for WCAG 2.1 AA accessibility issues with smart crawling, axe-core analysis, and deduplication'
branding:
  icon: 'eye'
  color: 'orange'

inputs:
  url:
    description: 'The URL to scan for accessibility issues'
    required: true
  max-pages:
    description: 'Maximum number of pages to crawl (1-100)'
    required: false
    default: '50'
  max-depth:
    description: 'Maximum crawl depth (1-5)'
    required: false
    default: '3'
  threshold:
    description: 'Minimum accessibility score to pass (0-100). Action fails if score is below this.'
    required: false
    default: '0'
  fail-on-critical:
    description: 'Fail the action if critical issues are found'
    required: false
    default: 'false'
  api-url:
    description: 'WCAG Crawler API endpoint URL'
    required: false
    default: 'https://wcag-crawler-server-production.up.railway.app'

outputs:
  score:
    description: 'The accessibility score (0-100)'
    value: ${{ steps.scan.outputs.score }}
  total-issues:
    description: 'Total number of unique issues found'
    value: ${{ steps.scan.outputs.total-issues }}
  critical-count:
    description: 'Number of critical issues'
    value: ${{ steps.scan.outputs.critical-count }}
  serious-count:
    description: 'Number of serious issues'
    value: ${{ steps.scan.outputs.serious-count }}
  moderate-count:
    description: 'Number of moderate issues'
    value: ${{ steps.scan.outputs.moderate-count }}
  minor-count:
    description: 'Number of minor issues'
    value: ${{ steps.scan.outputs.minor-count }}
  report-url:
    description: 'URL to the full scan report'
    value: ${{ steps.scan.outputs.report-url }}
  scan-id:
    description: 'The scan ID for API queries'
    value: ${{ steps.scan.outputs.scan-id }}

runs:
  using: 'composite'
  steps:
    - name: Run WCAG Scan
      id: scan
      shell: bash
      run: node "${{ github.action_path }}/action/index.js"
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_MAX_PAGES: ${{ inputs.max-pages }}
        INPUT_MAX_DEPTH: ${{ inputs.max-depth }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
        INPUT_FAIL_ON_CRITICAL: ${{ inputs.fail-on-critical }}
        INPUT_API_URL: ${{ inputs.api-url }}
